services:
  avibe:
    image: itzg/minecraft-server
    container_name: a_vibe

    ports:
      - 25565:25565
      
    restart: always

    volumes:
      - ./modpacks:/modpacks:ro
      - ./data:/data

    environment:
      EULA: "true"

      MOD_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: $$2a$$10$$3OryZ3vqXWXOOT48JxA2WOaDuowdeOY7G.v3Fxke6YZ1j/pSnjX/C
      CF_MODPACK_ZIP: /modpacks/A_Vibe_SERVER-V4.zip
      CF_SLUG: "custom"

      MEMORY: "12G"

      ENABLE_ROLLING_LOGS: "true"

      OVERRIDE_SERVER_PROPERTIES: "true"
      DIFFICULTY: "normal"
      MAX_TICK_TIME: "-1"
      ALLOW_FLIGHT: "true"
      OPS: ""
      VIEW_DISTANCE: 10
      MAX_PLAYERS: 20
      PVP: "false"
      LEVEL_TYPE: "biomesoplenty"
      MOTD: "Welcome Home"

volumes:
  data: {}